services:
  # Backend API Service
  - type: web
    name: dental-xray-api
    env: python
    region: oregon
    plan: starter
    buildCommand: cd backend && pip install --no-cache-dir -r requirements.txt
    startCommand: cd backend && gunicorn main:app --workers 1 --timeout 120 --preload --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: WEB_CONCURRENCY
        value: 1
      - key: ROBOFLOW_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TEST_MODE
        value: "False"
    autoDeploy: false
    healthCheckPath: /api/v1/health
    disk:
      name: uploads
      mountPath: /app/backend/uploads
      sizeGB: 1

  # Frontend Static Site
  - type: web
    name: dental-xray-web
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: "https://python-cmab.onrender.com"
